server:
  port: 7009

spring:
  application:
    name: cloud-consul-producer-7009

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}