server:
  port: 7080

  url: 127.0.0.1:8848

spring:
  cloud:
    nacos:
      config:
        server-addr: ${server.url}
        enabled: false
      discovery:
        server-addr: ${server.url}



  application:
    name: cloud-nacos-server-7080
