server:
  port: 7013

spring:
  application:
    name: cloud-ribbon-client-producer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/