server:
  port: 7020

spring:
  application:
    name: cloud-gateway-7070

  cloud:
    gateway:
      routes:
        #路由的id，没有固定规则要求唯一即可，建议使用服务名
        - id: cloud-payment-producer-service
          #匹配后提供服务的路由地址
          uri:  http://localhost:7003
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/discovery
#        - id: cloud-order-consumer-service
#          uri:  http://localhost:7002
#          predicates:
#            - Path=/index



eureka:
  instance:
    hostname: cloud-gateway-7070
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    register-with-eureka: true
    fetch-registry: true
