server:
  port: 7023

spring:
  cloud:
    config:
      server:
        git:
          #远程git地址
          uri: https://github.com/yechenglang/springcloud-config.git
          search-paths:
            - springcloud-config
      #读取分支
      label: main
  application:
    name: cloud-config-server-7023

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
