server:
  port: 7017


spring:
  application:
    name: cloud-hystrix-client-producer-7017


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/