server:
  port: 7010

spring:
  application:
    name: cloud-consul-consumer-7010

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}