server:
  port: 7016

spring:
  application:
    name: cloud-openfeign-client-consumer-7016

#设置feign超时时间（Feign默认支持Ribbon）
ribbon:
  #建立连接所需时间
  ReadTimeout: 5000
  #读取资源所需时间
  ConnectTimeout: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/


logging:
  level:
    #feign日志以什么级别监控那个接口
    cn.cloud.ycl.feign.FeignService: debug