server:
  port: 7002

spring:
  application:
    name: cloud-order-consumer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/