server:
  port: 7021

spring:
  application:
    name: cloud-gateway-7021

  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        #路由的id，没有固定规则要求唯一即可，建议使用服务名
        - id: cloud-ribbon-client-producer1
          #匹配后提供服务的路由地址
#          uri:  http://localhost:7003
          uri:  lb://cloud-ribbon-client-producer
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/index



eureka:
  instance:
    hostname: cloud-gateway-7070
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    register-with-eureka: true
    fetch-registry: true
